// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/sqlc-dev/pqtype"
)

type AuditAction string

const (
	AuditActionCREATE      AuditAction = "CREATE"
	AuditActionUPDATE      AuditAction = "UPDATE"
	AuditActionDELETE      AuditAction = "DELETE"
	AuditActionLOGIN       AuditAction = "LOGIN"
	AuditActionLOGOUT      AuditAction = "LOGOUT"
	AuditActionLOGINFAILED AuditAction = "LOGIN_FAILED"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type Admin struct {
	ID         uuid.UUID      `json:"id"`
	Firstname  sql.NullString `json:"firstname"`
	Middlename sql.NullString `json:"middlename"`
	Lastname   sql.NullString `json:"lastname"`
	Email      string         `json:"email"`
	Password   string         `json:"password"`
	Type       string         `json:"type"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
}

type AdminNotification struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Title      string         `json:"title"`
	Link       sql.NullString `json:"link"`
	ReadStatus bool           `json:"read_status"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type ApiKey struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	CompanyID uuid.UUID    `json:"company_id"`
	Name      string       `json:"name"`
	ApiKey    string       `json:"api_key"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type AuditLog struct {
	ID          uuid.UUID             `json:"id"`
	UserID      uuid.UUID             `json:"user_id"`
	Action      AuditAction           `json:"action"`
	Resource    string                `json:"resource"`
	ResourceID  uuid.NullUUID         `json:"resource_id"`
	Method      sql.NullString        `json:"method"`
	Endpoint    sql.NullString        `json:"endpoint"`
	IpAddress   pqtype.Inet           `json:"ip_address"`
	OccurredAt  time.Time             `json:"occurred_at"`
	Success     sql.NullBool          `json:"success"`
	RequestBody pqtype.NullRawMessage `json:"request_body"`
	Changes     pqtype.NullRawMessage `json:"changes"`
}

type Campaign struct {
	ID             uuid.UUID      `json:"id"`
	CompanyID      uuid.UUID      `json:"company_id"`
	Name           string         `json:"name"`
	Subject        sql.NullString `json:"subject"`
	PreviewText    sql.NullString `json:"preview_text"`
	UserID         uuid.UUID      `json:"user_id"`
	SenderFromName sql.NullString `json:"sender_from_name"`
	TemplateID     uuid.NullUUID  `json:"template_id"`
	SentTemplateID uuid.NullUUID  `json:"sent_template_id"`
	RecipientInfo  sql.NullString `json:"recipient_info"`
	IsPublished    sql.NullBool   `json:"is_published"`
	Status         sql.NullString `json:"status"`
	TrackType      sql.NullString `json:"track_type"`
	IsArchived     sql.NullBool   `json:"is_archived"`
	SentAt         sql.NullTime   `json:"sent_at"`
	Sender         sql.NullString `json:"sender"`
	ScheduledAt    sql.NullTime   `json:"scheduled_at"`
	HasCustomLogo  sql.NullBool   `json:"has_custom_logo"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type CampaignError struct {
	ID           uuid.UUID      `json:"id"`
	CampaignID   uuid.UUID      `json:"campaign_id"`
	ErrorType    sql.NullString `json:"error_type"`
	ErrorMessage string         `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
}

type CampaignGroup struct {
	ID             uuid.UUID    `json:"id"`
	CampaignID     uuid.UUID    `json:"campaign_id"`
	ContactGroupID uuid.UUID    `json:"contact_group_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type Company struct {
	ID          uuid.UUID      `json:"id"`
	Companyname sql.NullString `json:"companyname"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Contact struct {
	ID           uuid.UUID    `json:"id"`
	CompanyID    uuid.UUID    `json:"company_id"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
	Email        string       `json:"email"`
	FromOrigin   string       `json:"from_origin"`
	IsSubscribed sql.NullBool `json:"is_subscribed"`
	UserID       uuid.UUID    `json:"user_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type ContactGroup struct {
	ID          uuid.UUID      `json:"id"`
	CompanyID   uuid.UUID      `json:"company_id"`
	GroupName   string         `json:"group_name"`
	UserID      uuid.UUID      `json:"user_id"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Domain struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	CompanyID      uuid.UUID      `json:"company_id"`
	Domain         string         `json:"domain"`
	TxtRecord      sql.NullString `json:"txt_record"`
	DmarcRecord    sql.NullString `json:"dmarc_record"`
	DkimSelector   sql.NullString `json:"dkim_selector"`
	DkimPublicKey  sql.NullString `json:"dkim_public_key"`
	DkimPrivateKey sql.NullString `json:"dkim_private_key"`
	SpfRecord      sql.NullString `json:"spf_record"`
	Verified       sql.NullBool   `json:"verified"`
	MxRecord       sql.NullString `json:"mx_record"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type EmailBox struct {
	ID        uuid.UUID      `json:"id"`
	UserName  sql.NullString `json:"user_name"`
	From      sql.NullString `json:"from"`
	To        sql.NullString `json:"to"`
	Content   []byte         `json:"content"`
	Mailbox   sql.NullString `json:"mailbox"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type EmailCampaignResult struct {
	ID              uuid.UUID      `json:"id"`
	CompanyID       uuid.UUID      `json:"company_id"`
	CampaignID      uuid.UUID      `json:"campaign_id"`
	RecipientEmail  string         `json:"recipient_email"`
	RecipientName   sql.NullString `json:"recipient_name"`
	Version         sql.NullString `json:"version"`
	SentAt          sql.NullTime   `json:"sent_at"`
	OpenedAt        sql.NullTime   `json:"opened_at"`
	OpenCount       sql.NullInt32  `json:"open_count"`
	ClickedAt       sql.NullTime   `json:"clicked_at"`
	ClickCount      sql.NullInt32  `json:"click_count"`
	ConversionAt    sql.NullTime   `json:"conversion_at"`
	BounceStatus    sql.NullString `json:"bounce_status"`
	UnsubscribedAt  sql.NullTime   `json:"unsubscribed_at"`
	ComplaintStatus sql.NullBool   `json:"complaint_status"`
	DeviceType      sql.NullString `json:"device_type"`
	Location        sql.NullString `json:"location"`
	RetryCount      sql.NullInt32  `json:"retry_count"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type EmailUsage struct {
	ID               uuid.UUID     `json:"id"`
	CompanyID        uuid.UUID     `json:"company_id"`
	SubscriptionID   uuid.UUID     `json:"subscription_id"`
	UsagePeriodStart time.Time     `json:"usage_period_start"`
	UsagePeriodEnd   time.Time     `json:"usage_period_end"`
	PeriodType       string        `json:"period_type"`
	EmailsSent       sql.NullInt32 `json:"emails_sent"`
	EmailsLimit      int32         `json:"emails_limit"`
	CreatedAt        sql.NullTime  `json:"created_at"`
	UpdatedAt        sql.NullTime  `json:"updated_at"`
	RemainingEmails  sql.NullInt32 `json:"remaining_emails"`
}

type Invitation struct {
	ID         uuid.UUID     `json:"id"`
	CompanyID  uuid.UUID     `json:"company_id"`
	InvitedBy  uuid.UUID     `json:"invited_by"`
	Email      string        `json:"email"`
	Token      string        `json:"token"`
	Status     string        `json:"status"`
	ExpiresAt  time.Time     `json:"expires_at"`
	AcceptedAt sql.NullTime  `json:"accepted_at"`
	AcceptedBy uuid.NullUUID `json:"accepted_by"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
	DeletedAt  sql.NullTime  `json:"deleted_at"`
}

type JobExecutionLog struct {
	ID            uuid.UUID             `json:"id"`
	JobScheduleID uuid.NullUUID         `json:"job_schedule_id"`
	JobName       string                `json:"job_name"`
	StartedAt     time.Time             `json:"started_at"`
	FinishedAt    sql.NullTime          `json:"finished_at"`
	Status        string                `json:"status"`
	DurationMs    sql.NullInt32         `json:"duration_ms"`
	ErrorMessage  sql.NullString        `json:"error_message"`
	OutputData    pqtype.NullRawMessage `json:"output_data"`
	CreatedAt     sql.NullTime          `json:"created_at"`
}

type JobSchedule struct {
	ID             uuid.UUID      `json:"id"`
	JobName        string         `json:"job_name"`
	JobType        string         `json:"job_type"`
	CronSchedule   string         `json:"cron_schedule"`
	Enabled        sql.NullBool   `json:"enabled"`
	Description    sql.NullString `json:"description"`
	TimeoutSeconds sql.NullInt32  `json:"timeout_seconds"`
	MaxRetries     sql.NullInt32  `json:"max_retries"`
	LastRunAt      sql.NullTime   `json:"last_run_at"`
	LastSuccessAt  sql.NullTime   `json:"last_success_at"`
	LastFailureAt  sql.NullTime   `json:"last_failure_at"`
	FailureCount   sql.NullInt32  `json:"failure_count"`
	TotalRuns      sql.NullInt32  `json:"total_runs"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type MailingLimit struct {
	ID                   uuid.UUID     `json:"id"`
	PlanID               uuid.UUID     `json:"plan_id"`
	DailyLimit           sql.NullInt32 `json:"daily_limit"`
	MonthlyLimit         sql.NullInt32 `json:"monthly_limit"`
	MaxRecipientsPerMail sql.NullInt32 `json:"max_recipients_per_mail"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
	DeletedAt            sql.NullTime  `json:"deleted_at"`
}

type Otp struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

type Payment struct {
	ID                   uuid.UUID       `json:"id"`
	CompanyID            uuid.UUID       `json:"company_id"`
	UserID               uuid.UUID       `json:"user_id"`
	SubscriptionID       uuid.UUID       `json:"subscription_id"`
	PaymentID            sql.NullString  `json:"payment_id"`
	Amount               decimal.Decimal `json:"amount"`
	Currency             sql.NullString  `json:"currency"`
	PaymentMethod        sql.NullString  `json:"payment_method"`
	Status               sql.NullString  `json:"status"`
	Notes                sql.NullString  `json:"notes"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
	DeletedAt            sql.NullTime    `json:"deleted_at"`
	TransactionReference sql.NullString  `json:"transaction_reference"`
	PaymentDate          sql.NullTime    `json:"payment_date"`
	BillingPeriodStart   sql.NullTime    `json:"billing_period_start"`
	BillingPeriodEnd     sql.NullTime    `json:"billing_period_end"`
	RefundedAmount       decimal.Decimal `json:"refunded_amount"`
	IntegrityHash        sql.NullString  `json:"integrity_hash"`
	RefundDate           sql.NullTime    `json:"refund_date"`
}

type PaymentIntent struct {
	ID                      uuid.UUID             `json:"id"`
	CompanyID               uuid.UUID             `json:"company_id"`
	UserID                  uuid.UUID             `json:"user_id"`
	SubscriptionID          uuid.NullUUID         `json:"subscription_id"`
	PaymentIntentID         string                `json:"payment_intent_id"`
	Amount                  decimal.Decimal       `json:"amount"`
	Currency                sql.NullString        `json:"currency"`
	PaymentMethodTypes      []string              `json:"payment_method_types"`
	Status                  sql.NullString        `json:"status"`
	ClientSecret            sql.NullString        `json:"client_secret"`
	Description             sql.NullString        `json:"description"`
	Metadata                pqtype.NullRawMessage `json:"metadata"`
	AutomaticPaymentMethods sql.NullBool          `json:"automatic_payment_methods"`
	ReceiptEmail            sql.NullString        `json:"receipt_email"`
	SetupFutureUsage        sql.NullString        `json:"setup_future_usage"`
	ConfirmationMethod      sql.NullString        `json:"confirmation_method"`
	CaptureMethod           sql.NullString        `json:"capture_method"`
	PaymentMethodID         sql.NullString        `json:"payment_method_id"`
	LastPaymentError        pqtype.NullRawMessage `json:"last_payment_error"`
	NextAction              pqtype.NullRawMessage `json:"next_action"`
	CanceledAt              sql.NullTime          `json:"canceled_at"`
	SucceededAt             sql.NullTime          `json:"succeeded_at"`
	ExpiresAt               sql.NullTime          `json:"expires_at"`
	CreatedAt               sql.NullTime          `json:"created_at"`
	UpdatedAt               sql.NullTime          `json:"updated_at"`
	DeletedAt               sql.NullTime          `json:"deleted_at"`
}

type Plan struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	Description  sql.NullString  `json:"description"`
	Price        decimal.Decimal `json:"price"`
	BillingCycle sql.NullString  `json:"billing_cycle"`
	Status       sql.NullString  `json:"status"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	DeletedAt    sql.NullTime    `json:"deleted_at"`
}

type PlanFeature struct {
	ID          uuid.UUID      `json:"id"`
	PlanID      uuid.UUID      `json:"plan_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Value       sql.NullString `json:"value"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Sender struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	CompanyID uuid.UUID     `json:"company_id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Verified  sql.NullBool  `json:"verified"`
	IsSigned  sql.NullBool  `json:"is_signed"`
	DomainID  uuid.NullUUID `json:"domain_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}

type SentEmail struct {
	ID             uuid.UUID    `json:"id"`
	CompanyID      uuid.UUID    `json:"company_id"`
	SenderID       uuid.UUID    `json:"sender_id"`
	Recipient      string       `json:"recipient"`
	MessageContent string       `json:"message_content"`
	Status         string       `json:"status"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type SmtpKey struct {
	ID        uuid.UUID    `json:"id"`
	CompanyID uuid.UUID    `json:"company_id"`
	UserID    uuid.UUID    `json:"user_id"`
	KeyName   string       `json:"key_name"`
	Password  string       `json:"password"`
	Status    string       `json:"status"`
	SmtpLogin string       `json:"smtp_login"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type SmtpMasterKey struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	CompanyID uuid.UUID    `json:"company_id"`
	SmtpLogin string       `json:"smtp_login"`
	KeyName   string       `json:"key_name"`
	Password  string       `json:"password"`
	Status    string       `json:"status"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Subscription struct {
	ID                 uuid.UUID       `json:"id"`
	CompanyID          uuid.UUID       `json:"company_id"`
	PlanID             uuid.UUID       `json:"plan_id"`
	Amount             decimal.Decimal `json:"amount"`
	BillingCycle       sql.NullString  `json:"billing_cycle"`
	TrialStartsAt      sql.NullTime    `json:"trial_starts_at"`
	TrialEndsAt        sql.NullTime    `json:"trial_ends_at"`
	StartsAt           sql.NullTime    `json:"starts_at"`
	EndsAt             sql.NullTime    `json:"ends_at"`
	Status             sql.NullString  `json:"status"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	DeletedAt          sql.NullTime    `json:"deleted_at"`
	NextBillingDate    sql.NullTime    `json:"next_billing_date"`
	AutoRenew          sql.NullBool    `json:"auto_renew"`
	CancellationReason sql.NullString  `json:"cancellation_reason"`
	LastPaymentDate    sql.NullTime    `json:"last_payment_date"`
}

type SubscriptionUsage struct {
	ID             uuid.UUID     `json:"id"`
	UserID         uuid.UUID     `json:"user_id"`
	CompanyID      uuid.UUID     `json:"company_id"`
	SubscriptionID uuid.UUID     `json:"subscription_id"`
	FeatureName    string        `json:"feature_name"`
	UsedCount      sql.NullInt32 `json:"used_count"`
	MaxAllowed     sql.NullInt32 `json:"max_allowed"`
	ResetAt        time.Time     `json:"reset_at"`
	CreatedAt      sql.NullTime  `json:"created_at"`
	UpdatedAt      sql.NullTime  `json:"updated_at"`
	DeletedAt      sql.NullTime  `json:"deleted_at"`
}

type SupportTicket struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	Subject      string         `json:"subject"`
	Description  sql.NullString `json:"description"`
	TicketNumber string         `json:"ticket_number"`
	Status       sql.NullString `json:"status"`
	Priority     sql.NullString `json:"priority"`
	LastReply    sql.NullTime   `json:"last_reply"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type SystemsSmtpSetting struct {
	ID             uuid.UUID      `json:"id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	TxtRecord      sql.NullString `json:"txt_record"`
	DmarcRecord    sql.NullString `json:"dmarc_record"`
	DkimSelector   sql.NullString `json:"dkim_selector"`
	DkimPublicKey  sql.NullString `json:"dkim_public_key"`
	DkimPrivateKey sql.NullString `json:"dkim_private_key"`
	SpfRecord      sql.NullString `json:"spf_record"`
	Verified       sql.NullBool   `json:"verified"`
	MxRecord       sql.NullString `json:"mx_record"`
	Domain         sql.NullString `json:"domain"`
}

type Template struct {
	ID                uuid.UUID             `json:"id"`
	UserID            uuid.NullUUID         `json:"user_id"`
	CompanyID         uuid.NullUUID         `json:"company_id"`
	TemplateName      string                `json:"template_name"`
	SenderName        sql.NullString        `json:"sender_name"`
	FromEmail         sql.NullString        `json:"from_email"`
	Subject           sql.NullString        `json:"subject"`
	Type              string                `json:"type"`
	EmailHtml         sql.NullString        `json:"email_html"`
	EmailDesign       pqtype.NullRawMessage `json:"email_design"`
	IsEditable        sql.NullBool          `json:"is_editable"`
	IsPublished       sql.NullBool          `json:"is_published"`
	IsPublicTemplate  sql.NullBool          `json:"is_public_template"`
	IsGalleryTemplate sql.NullBool          `json:"is_gallery_template"`
	Tags              sql.NullString        `json:"tags"`
	Description       sql.NullString        `json:"description"`
	ImageUrl          sql.NullString        `json:"image_url"`
	IsActive          sql.NullBool          `json:"is_active"`
	EditorType        sql.NullString        `json:"editor_type"`
	CreatedAt         sql.NullTime          `json:"created_at"`
	UpdatedAt         sql.NullTime          `json:"updated_at"`
	DeletedAt         sql.NullTime          `json:"deleted_at"`
}

type TicketFile struct {
	ID        uuid.UUID `json:"id"`
	MessageID uuid.UUID `json:"message_id"`
	FileName  string    `json:"file_name"`
	FilePath  string    `json:"file_path"`
}

type TicketMessage struct {
	ID        uuid.UUID    `json:"id"`
	TicketID  uuid.UUID    `json:"ticket_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Message   string       `json:"message"`
	IsAdmin   sql.NullBool `json:"is_admin"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type User struct {
	ID                   uuid.UUID      `json:"id"`
	Fullname             string         `json:"fullname"`
	CompanyID            uuid.UUID      `json:"company_id"`
	Email                string         `json:"email"`
	Phonenumber          sql.NullString `json:"phonenumber"`
	Password             sql.NullString `json:"password"`
	GoogleID             sql.NullString `json:"google_id"`
	Picture              sql.NullString `json:"picture"`
	Verified             bool           `json:"verified"`
	Blocked              bool           `json:"blocked"`
	VerifiedAt           sql.NullTime   `json:"verified_at"`
	Status               string         `json:"status"`
	ScheduledForDeletion bool           `json:"scheduled_for_deletion"`
	ScheduledDeletionAt  sql.NullTime   `json:"scheduled_deletion_at"`
	LastLoginAt          sql.NullTime   `json:"last_login_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            sql.NullTime   `json:"deleted_at"`
}

type UserContactGroup struct {
	ID             uuid.UUID    `json:"id"`
	UserID         uuid.UUID    `json:"user_id"`
	ContactGroupID uuid.UUID    `json:"contact_group_id"`
	ContactID      uuid.UUID    `json:"contact_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type UserNotification struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Title           string    `json:"title"`
	ReadStatus      bool      `json:"read_status"`
	AdditionalField string    `json:"additional_field"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
