// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	BlockUser(ctx context.Context, id uuid.UUID) error
	CreateCompany(ctx context.Context, companyname sql.NullString) (Company, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	ListUsersByCompany(ctx context.Context, companyID uuid.UUID) ([]User, error)
	SoftDeleteCompany(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateUserLoginTime(ctx context.Context, id uuid.UUID) error
	VerifyUser(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
