version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: dev-crabmailer-traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"  # Dashboard for development
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard (http://localhost:8080)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`staging.crabmailer.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=6000"
    networks:
      - app-network
    depends_on:
      - go-backend

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  go-backend:
    container_name: crabmailer-staging-api
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    labels:
      - "traefik.enable=true"
      # API HTTP
      - "traefik.http.routers.api.rule=Host(`api.staging.crabmailer.com`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=9000"
      # WebSocket routing
      - "traefik.http.routers.ws.rule=Host(`api.staging.crabmailer.com`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.ws.entrypoints=web"
      - "traefik.http.services.ws.loadbalancer.server.port=9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # WebSockets
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - smtp_settings:/app/backend/smtp_settings
      - uploads:/app/backend/uploads
      - templates:/app/backend/api/v1/templates
      - logs:/app/backend/logs
    cap_add:
      - NET_BIND_SERVICE
    privileged: true
    env_file: ./backend/.env
    environment:
      SERVER_MODE: "production"
      REDIS_ADDR: "redis:6379"
      DISABLE_TLS: "true"
    depends_on:
      - redis
      - postgres-db

  postgres-db:
    container_name: crabmailer-staging-postgres-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  smtp_settings:
    driver: local
  uploads:
    driver: local
  templates:
    driver: local
  logs:
    driver: local
  postgres_data:
    driver: local