services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:80"
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - go-backend

  go-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
      - "1025:1025"
      - "465:465" # SMTPS port
    environment:
      SERVER_MODE: "production"
    env_file: ./backend/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./backend:/app/backend
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount host certificates
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro # Mount letsencrypt data
    cap_add:
      - NET_BIND_SERVICE
    privileged: true

networks:
  app-network:
    driver: bridge
