version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "1025:1025"  # SMTP port
    environment:  
      SERVER_MODE: "production"
    env_file: ./backend/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Updated path to the root directory
    depends_on:
      app:
        condition: service_healthy
    networks:
      - app-network
    command: /bin/sh -c "nginx -g 'daemon off;'"

networks:
  app-network:
    driver: bridge
