services:
  
  nginx:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:80"
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx # Add persistent logs
    networks:
      - app-network
    depends_on:
      - go-backend

  go-backend:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
      - "1025:1025"
      - "465:465"
      - "9001:9001"
    environment:
      SERVER_MODE: "production"
    env_file: ./backend/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Specific named volumes for different data types
      - smtp_settings:/app/backend/smtp_settings
      - uploads:/app/backend/uploads
      - templates:/app/backend/api/v1/templates
      - /etc/letsencrypt:/etc/letsencrypt:ro # Commented SSL certs
    cap_add:
      - NET_BIND_SERVICE
    privileged: true # Consider removing if possible for security

networks:
  app-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
  smtp_settings:
    driver: local
  uploads:
    driver: local
  templates:
    driver: local
