services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "9000:9000"
      - "1027:1025"
    environment:
      SERVER_MODE: "test"
    env_file: ./backend/.env.test
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./backend:/app
    cap_add:
      - NET_BIND_SERVICE
    privileged: true # Be cautious with this in production

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      go-backend:
        condition: service_healthy
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1026:1025" # SMTP
      - "8026:8025" # Web UI
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    env_file: ./backend/.env.test
    environment:
      POSTGRES_DB: "email_marketing_service"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "lorenzo"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
