WIRE_PATH := ./backend/api/v1/routes
MAIN_PATH := ./backend/api/v1
ROOT_DIR := ./backend/
FE_DIR := ./frontend/
DIST_DIR := $(FE_DIR)dist
CLIENT_DIR := $(ROOT_DIR)client
SMTP_DIR := ./smtp/
.PHONY: wire build

wire:
	cd $(WIRE_PATH) && wire

run:
	cd $(ROOT_DIR) && go run .

build:
	cd $(ROOT_DIR) && go build main.go

air:
	cd $(ROOT_DIR) && air

npmi:
	cd $(FE_DIR) && npm i $(ARGS)

rundev:
	cd $(FE_DIR) && npm run dev

buildfe:
	cd $(FE_DIR) && npm run build
ifeq ($(OS),Windows_NT)
	powershell -Command "if (Test-Path $(subst /,\,$(CLIENT_DIR))) { Remove-Item -Recurse -Force $(subst /,\,$(CLIENT_DIR)) }"
	powershell -Command "New-Item -ItemType Directory -Force -Path $(subst /,\,$(CLIENT_DIR))"
	powershell -Command "Copy-Item -Path '$(subst /,\,$(DIST_DIR))\*' -Destination '$(subst /,\,$(CLIENT_DIR))' -Recurse -Force"
else
	rm -rf $(CLIENT_DIR)
	mkdir -p $(CLIENT_DIR)
	cp -r $(DIST_DIR)/* $(CLIENT_DIR)/
endif

git:
	git add .
	git commit -m "done"
	git push

docker:
	docker-compose up --build -d

vet:
	cd $(ROOT_DIR) && go vet

start-smtp:
	cd $(SMTP_DIR) && air 
	