export { default as LoginTemplate } from './Login'
export { default as SignUpTemplate } from './SignUp'
export { default as OTPTemplate } from './OTP'
export { default as ForgotPasswordTemplate } from './ForgotPassword'
export { default as ResetPasswordTemplate } from './ResetPassword'