export { default as APIKeysComponentTable } from './Settings/apiComponentTable'
export { default as SMTPKeysTableComponent } from './Settings/smtpComponentTable'
export { default as DeleteAccountComponent } from './Settings/DeleteAccountComponent'
export { default as ProfileInformationComponent } from './Settings/ProfileInformationComponent'
export { default as ChangePasswordComponent } from './Settings/changePasswordComponent'
