// Define the shape of the metadata properties
interface MetadataProps {
    title: string;
    description: string;
    keywords: string;
    type: string;
    url: string;
    image: string;
    locale: string;
    siteName: string;
    twitterCard: string;
    twitterSite: string;
    twitterCreator: string;
    ogType: string;
    ogUrl: string;
    ogImage: string;
    ogImageAlt: string;
    ogImageWidth: number;
    ogImageHeight: number;
    ogImageType: string;
    ogTitle: string;
    ogDescription: string;
    ogSiteName: string;
    ogLocale: string;
}


export const metadataConfig = {
    LandingPage: {
        title: "CrabMailer - Powerful Email Marketing Platform",
        description: "Grow your business with our easy-to-use email marketing tools. Sign up today!",
        keywords: "email marketing platform, email automation tools, email campaigns, newsletter management, subscriber growth",
        type: "website",
        url: import.meta.env.VITE_REACT_APP_BASE_URL,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: import.meta.env.VITE_REACT_APP_BASE_URL,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-hero.jpg`,
        ogImageAlt: "Email Marketing Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Powerful Email Marketing Platform - CrabMailer",
        ogDescription: "Grow your business with our easy-to-use email marketing tools. Sign up today!",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Signup: {
        title: "Sign Up - CrabMailer",
        description: "Create an account and start building your email marketing campaigns.",
        keywords: "email marketing signup, grow email list, campaign management",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/signup`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/signup`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        ogImageAlt: "CrabMailer Logo",
        ogImageWidth: 1200,
        ogImageHeight: 630,
        ogImageType: "image/png",
        ogTitle: "Sign Up - CrabMailer",
        ogDescription: "Create an account and start building your email marketing campaigns.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    ResetPassword: {
        title: "Reset Password - CrabMailer",
        description: "Reset your account password to access your email marketing tools.",
        keywords: "password reset, email marketing account security, password recovery",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/reset-password`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/reset-password`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        ogImageAlt: "CrabMailer Logo",
        ogImageWidth: 1200,
        ogImageHeight: 630,
        ogImageType: "image/png",
        ogTitle: "Reset Password - CrabMailer",
        ogDescription: "Reset your account password to access your email marketing tools.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    PrivacyPolicy: {
        title: "Privacy Policy - CrabMailer",
        description: "Understand how we handle your data and maintain your privacy.",
        keywords: "privacy policy, email marketing privacy, data protection, personal data security",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/privacy-policy`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/privacy-policy-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/privacy-policy`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/privacy-policy-hero.jpg`,
        ogImageAlt: "Privacy Policy Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Privacy Policy - CrabMailer",
        ogDescription: "Understand how we handle your data and maintain your privacy.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    TermsAndConditions: {
        title: "Terms and Conditions - CrabMailer",
        description: "Read the terms and conditions for using our email marketing platform.",
        keywords: "terms and conditions, email marketing service agreement, usage terms",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/terms-and-conditions`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/terms-conditions-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/terms-and-conditions`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/terms-conditions-hero.jpg`,
        ogImageAlt: "Terms and Conditions Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Terms and Conditions - CrabMailer",
        ogDescription: "Read the terms and conditions for using our email marketing platform.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    AccountVerification: {
        title: "Verify account - CrabMailer",
        description: "Verify your account to access you email marketing tools.",
        keywords: "email marketing password reset, account security, password recovery",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/reset-password`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/reset-password`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        ogImageAlt: "CrabMailer Logo",
        ogImageWidth: 1200,
        ogImageHeight: 630,
        ogImageType: "image/png",
        ogTitle: "Verify account - CrabMailer",
        ogDescription: "Verify your account to access your email marketing tools.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    ForgotPassword: {
        title: "Forgot Password - CrabMailer",
        description: "Recover your email marketing account by resetting your password.",
        keywords: "email marketing forgot password, password recovery, account access",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/forgot-password`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/forgot-password`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        ogImageAlt: "CrabMailer Logo",
        ogImageWidth: 1200,
        ogImageHeight: 630,
        ogImageType: "image/png",
        ogTitle: "Forgot Password - CrabMailer",
        ogDescription: "Recover your email marketing account by resetting your password.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Login: {
        title: "Login - CrabMailer",
        description: "Sign in to your email marketing account and manage your campaigns.",
        keywords: "email marketing login, account access, email campaign management",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/auth/login`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/login`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/email-marketing-logo.png`,
        ogImageAlt: "CrabMailer Logo",
        ogImageWidth: 1200,
        ogImageHeight: 630,
        ogImageType: "image/png",
        ogTitle: "Login - CrabMailer",
        ogDescription: "Sign in to your email marketing account and manage your campaigns.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    About: {
        title: "About - CrabMailer",
        description: "Learn more about our email marketing company and our mission to help businesses grow.",
        keywords: "email marketing company, email marketing services, about us",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/about`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/about-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/about`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/about-hero.jpg`,
        ogImageAlt: "About Us Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "About - CrabMailer",
        ogDescription: "Learn more about our email marketing company and our mission to help businesses grow.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    FAQ: {
        title: "FAQ - CrabMailer",
        description: "Frequently asked questions about our email marketing platform and services.",
        keywords: "email marketing FAQ, email marketing questions, email marketing support",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/faq`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/faq-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/faq`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/faq-hero.jpg`,
        ogImageAlt: "FAQ Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "FAQ - CrabMailer",
        ogDescription: "Frequently asked questions about our email marketing platform and services.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Contact: {
        title: "Contact - CrabMailer",
        description: "Get in touch with our team for more information about our email marketing services.",
        keywords: "email marketing contact, email marketing support, customer service",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/contact`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/contact-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/contact`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/contact-hero.jpg`,
        ogImageAlt: "Contact Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Contact - CrabMailer",
        ogDescription: "Get in touch with our team for more information about our email marketing services.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    ContactGroup: {
        title: "Contact Group - CrabMailer",
        description: "Manage your contact groups for effective email marketing.",
        keywords: "email marketing contact groups, audience segmentation, manage contacts",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/contact-groups`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/contact-groups-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/contact-groups`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/contact-groups-hero.jpg`,
        ogImageAlt: "Contact Group Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Contact Group - CrabMailer",
        ogDescription: "Manage your contact groups for effective email marketing.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Campaigns: {
        title: "Campaigns - CrabMailer",
        description: "Create and manage your email marketing campaigns.",
        keywords: "email marketing campaigns, create campaigns, campaign management",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/campaigns`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/campaigns-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/campaigns`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/campaigns-hero.jpg`,
        ogImageAlt: "Campaigns Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Campaigns - CrabMailer",
        ogDescription: "Create and manage your email marketing campaigns.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    ScheduledCampaigns: {
        title: "Scheduled Campaigns - CrabMailer",
        description: "View and manage your scheduled email marketing campaigns.",
        keywords: "scheduled campaigns, email marketing automation, campaign scheduling",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/scheduled-campaigns`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/scheduled-campaigns-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/scheduled-campaigns`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/scheduled-campaigns-hero.jpg`,
        ogImageAlt: "Scheduled Campaigns Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Scheduled Campaigns - CrabMailer",
        ogDescription: "View and manage your scheduled email marketing campaigns.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    MarketingTemplates: {
        title: "Marketing Templates - CrabMailer",
        description: "Explore and use our email marketing templates for your campaigns.",
        keywords: "email marketing templates, campaign templates, template gallery",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/marketing-templates`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/marketing-templates-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/marketing-templates`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/marketing-templates-hero.jpg`,
        ogImageAlt: "Marketing Templates Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Marketing Templates - CrabMailer",
        ogDescription: "Explore and use our email marketing templates for your campaigns.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    TransactionalTemplates: {
        title: "Transactional Templates - CrabMailer",
        description: "Manage your transactional email templates.",
        keywords: "transactional email templates, email automation, template management",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/transactional-templates`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/transactional-templates-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/transactional-templates`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/transactional-templates-hero.jpg`,
        ogImageAlt: "Transactional Templates Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Transactional Templates - CrabMailer",
        ogDescription: "Manage your transactional email templates.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Dashboard: {
        title: "Dashboard - CrabMailer",
        description: "Overview of your email marketing performance and analytics.",
        keywords: "email marketing dashboard, performance analytics, campaign overview",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/dashboard`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/dashboard-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/dashboard`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/dashboard-hero.jpg`,
        ogImageAlt: "Dashboard Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Dashboard - CrabMailer",
        ogDescription: "Overview of your email marketing performance and analytics.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    HelpAndSupport: {
        title: "Help and Support - CrabMailer",
        description: "Get help and support for using our email marketing platform.",
        keywords: "email marketing support, help center, customer support",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/help-and-support`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/help-support-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/help-and-support`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/help-support-hero.jpg`,
        ogImageAlt: "Help and Support Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Help and Support - CrabMailer",
        ogDescription: "Get help and support for using our email marketing platform.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },

    SupportTicket: {
        title: "Support Ticket - CrabMailer",
        description: "Submit and manage your support tickets.",
        keywords: "support ticket, email marketing help, ticket management",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/support-ticket`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/support-ticket-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/support-ticket`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/support-ticket-hero.jpg`,
        ogImageAlt: "Support Ticket Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Support Ticket - CrabMailer",
        ogDescription: "Submit and manage your support tickets.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Sender: {
        title: "Sender - CrabMailer",
        description: "Manage your email senders for effective communication.",
        keywords: "email sender management, sender setup, email communication",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/sender`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/sender-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/sender`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/sender-hero.jpg`,
        ogImageAlt: "Sender Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Sender - CrabMailer",
        ogDescription: "Manage your email senders for effective communication.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Domain: {
        title: "Domain - CrabMailer",
        description: "Manage your domains for email marketing.",
        keywords: "email marketing domains, domain management, domain setup",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/domain`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/domain-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/domain`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/domain-hero.jpg`,
        ogImageAlt: "Domain Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Domain - CrabMailer",
        ogDescription: "Manage your domains for email marketing.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Settings: {
        title: "Settings - CrabMailer",
        description: "Configure your account settings and preferences.",
        keywords: "email marketing settings, account preferences, settings management",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/settings`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/settings-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/settings`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/settings-hero.jpg`,
        ogImageAlt: "Settings Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Settings - CrabMailer",
        ogDescription: "Configure your account settings and preferences.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Billing: {
        title: "Billing - CrabMailer",
        description: "Manage your billing information and payment methods.",
        keywords: "billing, payment methods, subscription management",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/billing`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/billing-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/billing`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/billing-hero.jpg`,
        ogImageAlt: "Billing Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Billing - CrabMailer",
        ogDescription: "Manage your billing information and payment methods.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Plan: {
        title: "Plan - CrabMailer",
        description: "View and select your subscription plan.",
        keywords: "subscription plans, pricing, email marketing plans",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/plan`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/plan-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/plan`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/plan-hero.jpg`,
        ogImageAlt: "Plan Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Plan - CrabMailer",
        ogDescription: "View and select your subscription plan.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },
    Profile: {
        title: "Profile - CrabMailer",
        description: "View and edit your profile information.",
        keywords: "user profile, profile settings, account management",
        type: "website",
        url: `${import.meta.env.VITE_REACT_APP_BASE_URL}/profile`,
        image: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/profile-hero.jpg`,
        locale: "en_US",
        siteName: "CrabMailer",
        twitterCard: "summary_large_image",
        twitterSite: "@youremailcompany",
        twitterCreator: "@youremailcompany",
        ogType: "website",
        ogUrl: `${import.meta.env.VITE_REACT_APP_BASE_URL}/profile`,
        ogImage: `${import.meta.env.VITE_REACT_APP_BASE_URL}/images/profile-hero.jpg`,
        ogImageAlt: "Profile Hero Image",
        ogImageWidth: 1920,
        ogImageHeight: 1080,
        ogImageType: "image/jpeg",
        ogTitle: "Profile - CrabMailer",
        ogDescription: "View and edit your profile information.",
        ogSiteName: "CrabMailer",
        ogLocale: "en_US",
    },

} as const satisfies Record<string, MetadataProps> 