
name: CI

on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Copy project contents to /home/ubuntu/apps/email-marketing-service
    - name: Copy project to target directory
      run: |
        sudo mkdir -p /home/ubuntu/apps/email-marketing-service
        sudo cp -r ${{ github.workspace }}/* /home/ubuntu/apps/email-marketing-service/

    - name: Run docker-restart
      # Run make docker-restart in the target directory
      working-directory: /home/ubuntu/apps/email-marketing-service
      run: |
        sudo make docker-restart
